import mongoose from "mongoose";

const InterviewSessionSchema = new mongoose.Schema(
  {
    user: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true, index: true },
    company: String,
    interviewType: { type: String, enum: ["HR", "Technical", "Behavioral", "Mixed"], default: "Mixed" },
    role: String,
    experienceLevel: String,
    difficulty: { type: String, enum: ["Easy", "Medium", "Hard"], default: "Medium" },
    duration: { type: Number, default: 10 },
    totalRounds: { type: Number, default: 7 },
    currentRound: { type: Number, default: 1 },
    videoUrl: String,
    videoMetadata: {
      duration: Number,
      size: Number,
      format: String,
    },
    questions: [
      {
        question: String,
        answer: String,
        time: Number,
        round: Number,
        roundName: String,
        scores: {
          communication: Number,
          confidence: Number,
          technical: Number,
          grammar: Number,
          fluency: Number,
          leadership: Number,
          problemSolving: Number,
          bodyLanguage: Number,
          eyeContact: Number,
          professionalism: Number,
          overall: Number,
        },
        feedback: String,
      },
    ],
    transcript: { type: String, default: "" },
    rounds: [
      {
        roundNumber: Number,
        roundName: String,
        questions: [String],
        answers: [String],
        roundScore: Number,
        roundFeedback: String,
      },
    ],
    communicationScore: Number,
    confidenceScore: Number,
    technicalScore: Number,
    grammarScore: Number,
    fluencyScore: Number,
    leadershipScore: Number,
    problemSolvingScore: Number,
    bodyLanguageScore: Number,
    eyeContactScore: Number,
    professionalismScore: Number,
    hrScore: Number,
    overallScore: Number,
    resumeMatchPercentage: Number,
    hiringRecommendation: String,
    careerReadinessScore: Number,
    recommendedSkills: [String],
    strengths: String,
    weaknesses: String,
    suggestions: String,
    improvementSuggestions: String,
    report: String,
  },
  { timestamps: true }
);

export default mongoose.model("InterviewSession", InterviewSessionSchema);
